spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb5?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*